<?php

use Drupal\search_api\Plugin\search_api\datasource\ContentEntity;

/**
 * @file
 * Contains archivio_utils.module.
 */

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function archivio_utils_node_update(Drupal\Core\Entity\EntityInterface $entity) {
  // Verifico se il tipo di contenuto è una carriera
  if ($entity->bundle() == 'carriera') {
    if (!$entity->get('field_persona')->isEmpty()) {
      $persone = $entity->get('field_persona')->referencedEntities();
      $persona = $persone[0];
      $indexes = ContentEntity::getIndexesForEntity($persona);
      foreach ($indexes as $index) {
        $index->trackItemsUpdated('entity:node', [$persona->id() . ':it']);
      }
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function archivio_utils_node_presave(Drupal\Core\Entity\EntityInterface $entity) {

  // Verifico se il tipo di contenuto è uno di quelli della carriera
  if ($entity->bundle() == 'carriera_studente' || $entity->bundle() == 'carriera_docente') {
    $persone = $entity->get('field_persona')->referencedEntities();
    $a = 1;
    /**
     * - se il nodo è nuovo, aggiorno la persona aggiungendo il link alla carriera appena creata
     * - se il nodo non è nuovo, verifico se è cambiato il link alla persona dal nodo originale ad adesso
     *     - se il link alla persona non è cambiato, non faccio niente (la persona deve già avere il link alla carriera). O al massimo verifico che la persona abbia il link alla carriera
     *     - se il link alla persona è cambiatoè cambiato devo fare due cose:
     *         - carico la persona "vecchia", dal nodo carriera originale, e tolgo il riferimento alla carriera che sto salvando
     *         - carico la "nuova" persona e imposto il riferimento alla carriera che sto salvando
     *
     */
  }
}

/**
 * Implements hook_form_alter().
 */
function archivio_utils_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

  $a = 1;
  if ($form_id == 'layout_builder_add_block') {
    $form['settings']['label_display']['#default_value'] = false;
    $form['settings']['label']['#title'] = 'Titolo amministrativo';
    $form['settings']['label']['#description'] = 'Il titolo amministrativo del blocco, non viene visualizzato nella pagina.';
  }

}
